[config]
data_dir=roms;x68k;msx;pce;pc88;pc98;mucom88
sampling_rate=44100
buffer=16

language=japanese.lng

; fft_winfnc
;  0 : rectangular
;  1 : Hanning
;  2 : Hamming
;  3 : Blackman
fft_size=1024
fft_winfunc=3
fft_skip=1

lpf=1
lpf_order=4
lpf_cutoff=10000

ym2151_interpolation=1
ym2151_volume=0

ym2203_interpolation=1
ym2203_volume_fm=0
ym2203_volume_psg=0

ym2608_interpolation=1
ym2608_volume_fm=0
ym2608_volume_psg=0
ym2608_volume_rhythmt=0
ym2608_volume_rhythm0=0
ym2608_volume_rhythm1=0
ym2608_volume_rhythm2=0
ym2608_volume_rhythm3=0
ym2608_volume_rhythm4=0
ym2608_volume_rhythm5=0
ym2608_volume_adpcm=0

ym2610_interpolation=1
ym2610_volume_fm=0
ym2610_volume_psg=0
ym2610_volume_adpcma=0
ym2610_volume_adpcmb=0

pdx_dir=c:\data\mdx\pdx
